### ISSUE TITLE
Implement limits and pagination options for API routes that return more than one resource

### ISSUE THREAD

**Issue by cbj4074** [indiehd/web-api#139]
*Any* API route has the potential to return more than one resource should permit the client to specify limit (how many records are returned) and pagination (how many records per "page") preferences. Upon a cursory analysis, it looks like this may best be done in the `ApiController`.

**Comment by poppabear8883** [comment]
I'm sure you mean that `only` the `index route` or `all() method` needs to allow a limit and/or pagination to be specified ... Not sure there are any other routes that will return multiple resources ?

**Comment by cbj4074** [comment]
Yes, exactly. Sorry for the ambiguity (I've updated the description to be more explicit).

**Comment by poppabear8883** [comment]
PR #141 Closes this issue
