### ISSUE TITLE
Consider making ApiController validation clearer

### ISSUE THREAD

**Issue by mblarsen** [indiehd/web-api#173]
(adopted from [Discord chat](https://discordapp.com/channels/474753427583270922/474753428665663507/721227919778906213))

Currently it is a bit unclear what happens when you read the action methods on the `ApiController`.

![https://cdn.discordapp.com/attachments/474753428665663507/721227919602614312/Screenshot_from_2020-06-13_13-00-36.png](https://cdn.discordapp.com/attachments/474753428665663507/721227919602614312/Screenshot_from_2020-06-13_13-00-36.png)

The a new update request is resolved and in doing so it will validate the incoming data. If the validation fails a ValidationException is thrown. 

All of that is fine, however, it is unclear and it is a bit of an anti-pattern to rely only on the side-effect, which is what happens here. The side-effect of resolving is validation. 

Also a `FormRequst` doesn't only have to validate. So not using the output from she resolved request and using the generic one instead is kind of not presenting the 100% quarantines that the specific request offer.

One way to improve the readability issue is to wrap the call in a function data tells you what happens:

```php
protected function validateRequest($requestClass): array
{
    return resolve($requestClass)->all();
}
```

and then use it like this:

```php
public function update($id)
{
    $data = $this->validateRequest($this->updateRequest());
    
    $this->repository->update($id, $data);

    ...
}
```

This achieves two things:

1. documentation 
2. ensure that the request data is the validated (and possibly transformed) data.

**Comment by cbj4074** [comment]
Thanks for pointing this out!

If you find the time to submit a PR to make this change, I'd be most appreciative! (Otherwise, I'm happy to do it.)
