### ISSUE TITLE
Tools for Artists

### ISSUE THREAD

**Issue by cbj4074** [indiehd/web-api#28]
Code Generator, for adding Artists to existing Label

**Comment by poppabear8883** [comment]
@cbj4074 can i get a bit more information on this ? I might want to take this on.

**Comment by cbj4074** [comment]
@poppabear8883 Sure!

If a User has an existing Account that is associated with an Artist profile, and he later decides to apply for a Label profile, too, there needs to be a means by which to associate the existing Artist with the new Label.

But in thinking this through more carefully, now that we've overhauled the underlying mechanisms by which Artists and Labels are associated with Users (this is done via the `CatalogEntity` model), it seems we can eliminate the need for this legacy tool altogether.

To explain a bit further, in the past, the relationship between User and Artist (or Label) was one-to-one, so a given User could not be associated with both an Artist and a Label. Accordingly, this Code Generator was necessary to prove that a Label account had login access to an Artist account before making the Artist-to-Label association.

With the new underlying design, the user can simply log into a single account and associate any Artist under his control with any Label under his control. Problem solved.

The only conceivable scenario in which we could still need a tool like this is if we intend to allow Users to move Artists and/or Labels from one account to the another; the User would have to prove that he controls both Accounts.

Does this make more sense now? Just let me know if not.

**Comment by poppabear8883** [comment]
Makes sense yes, imo regarding the moving/transferring of "Profiles" could be done as easily as the user clicking on a Transfer button and then is presented with the current account password, then validating the credentials of the receiving account, then it just transfers .. no need for a code generator imo.

**Comment by cbj4074** [comment]
Yes, even better. Let's go ahead and close this, then.
