### ISSUE TITLE
Update UserController

### ISSUE THREAD

**Issue by poppabear8883** [indiehd/web-api#51]
The current state of the `UserController` is not correct. It should be updated to properly implement the same patterns of the other controllers. Including validation ...

**Comment by poppabear8883** [comment]
To add to this issue, the `UserController` has obvious broken code which tells me we are missing a test for this controller. I suggest adding the test before closing this issue.

**Comment by cbj4074** [comment]
Yes, it looks like we haven't touched this since January, and much has changed.

I'll add the test and fix these issues.

**Comment by cbj4074** [comment]
Fixed in a413b859633bd3940cd44564016a351fdd6bb93f
