### ISSUE TITLE
Change password request validation

### ISSUE THREAD

**Issue by poppabear8883** [indiehd/web-api#53]
Create `UpdatePassword` with the appropriate validation rules.

**Comment by UncertaintyP** [comment]
Just had a quick look at your past broadcast, no sound so I dunno exactly whats going on.
+1 for Password Form Request but PLEASE don't restrict the password to be `alpha_dash` there is no sane reason to do this !!!
Don't use hard coded bcrypt but Laravel's hash (the user of the package wants to use bcrypt OR argon depending on configuration (or another one in the future ^^))

**Comment by poppabear8883** [comment]
The audio is cut because of the music that was playing, but yea i thought about that validation rule after I submitted it so i will remove it as suggested. I'm actually thinking there should be more to it. You can follow the WIP via PR #54

**Comment by cbj4074** [comment]
Much better. As @UncertaintyP suggested elsewhere, the length is irrelevant because the password will be hashed to a fixed length.

I don't see a need for any restriction beyond minimum length, the current value for which seems reasonable. :+1:
