### ISSUE TITLE
Add "username" column to "users" table and modify Sentinel configuration to use it

### ISSUE THREAD

**Issue by cbj4074** [indiehd/web-api#6]
There are a number of reasons for which using one's email address for authentication purposes is less than ideal, not least of which are:

1. Account security is reduced only to the password (because an email address is considered to be public knowledge).
2. A user cannot have more than one account with the same email address, which is hugely inconvenient given certain use-cases.

Accordingly, let's add a `username` column and authenticate against that, instead of `email`. To do so is trivially simple with Sentinel.

**Comment by poppabear8883** [comment]
I'm assuming this issue can be tagged `invalid` and closed dude to decisions to revert this back to email authentication ?

**Comment by cbj4074** [comment]
You assume correctly. 👍
