### ISSUE TITLE
Feature tests seem not to be executed against dedicated testing database

### ISSUE THREAD

**Issue by cbj4074** [indiehd/web-api#89]
Feature tests should be executed against a dedicated testing database, which is configured to be `indiehd_test`, but it seems that they are being executed against the primary database, `indiehd`.

I say this because a couple of us have noticed that the primary database is sometimes found to be empty after running tests, even though it was seeded just prior.

**Comment by cbj4074** [comment]
My instinct is that this behavior is simply a product of how the tests are initiated, and more specifically, that the `APP_ENV` value is not being propagated to PHPUnit.

This can absolutely happen if tests are initiated via an IDE, such as PhpStorm, e.g., by right-clicking on a class file, or in the margin next to a given test method when viewing a test class, and clicking choosing "Run ... (PHPUnit)".

I'm unable to reproduce this, even in PhpStorm, as long as I `phpunit` is started with `--configuration /home/vagrant/code/indiehd-web-api/phpunit.xml` (or wherever this file lives in the given environment).

@poppabear8883 Are you able to confirm this on your configuration?

**Comment by poppabear8883** [comment]
I am noticing that the `APP_ENV` in the `phpunit.xml` is set to `testing`, try replacing that with just `test` ...

**Comment by poppabear8883** [comment]
The above is the way I configured before when it was working as expected as can be seen here on the `dev` branch:

https://github.com/indiehd/web-api/blob/dev/phpunit.xml#L26

**Comment by cbj4074** [comment]
Doesn't that seem to be at odds with Laravel's default configuration, though?

Have a look here:

https://github.com/laravel/laravel/blob/master/phpunit.xml#L26

To be clear, I'm using the same value now, in my `phpunit.xml`, and everything seems to work as expected. The only thing I "fixed" to make this behave consistently when initiating tests from within various places within PhpStorm was to specify this same `phpunit.xml` as the default configuration file for tests.

**Comment by poppabear8883** [comment]
So you are saying that it only paves over the regular database when executing tests from with-in the IDE ?

**Comment by cbj4074** [comment]
Yes, exactly. That's what I observe.

**Comment by poppabear8883** [comment]
Let me confirm this in my environment as well .. will get back to you shortly

**Comment by poppabear8883** [comment]
So it appears i can confirm this:

![image](https://user-images.githubusercontent.com/7263458/45767460-3af9a680-bc08-11e8-9099-c7e8726f53cf.png)

I get the `0` result ***ONLY*** from running the tests from with-in the IDE ...

Thanks for hunting this issue down. You can close this if its fair to say that its invalid due to user error in configuring IDE properly

**Comment by cbj4074** [comment]
Excellent; thanks for confirming!

It may be worth adding something about this to the Contributor documentation.
